version: '3.3'

services:
  db:
    networks:
        - videoteca_default-network
    image: postgres:14
    environment:
      - POSTGRES_DB=videoteca
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/backups:/docker-entrypoint-initdb.d
      - videoteca_postgres_data:/var/lib/postgresql/data

  rh:
    networks:
      - videoteca_default-network
    image: postgres:14
    environment:
      - POSTGRES_DB=recursos_humanos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    volumes:
      - /var/lib/postgresql/backups:/docker-entrypoint-initdb.d
      - rh_postgres_data:/var/lib/postgresql/data

  web:
    networks:
      - videoteca_default-network
    build:
      context: .
      dockerfile: Dockerfile
    image: django:latest
    command: python manage.py runserver 0.0.0.0:8085
    volumes:
      - .:/app
    ports:
      - "8085:8085"
    depends_on:
      - db
      - rh
    environment:
      - DEBUG=False
    restart: always

volumes:
  videoteca_postgres_data:
  rh_postgres_data:

networks:
  videoteca_default-network:
    driver: bridge